### ISSUE TITLE
Unbalanced

### ISSUE THREAD

**Issue by DefinetlyNotAI** [Daniel-dev-s/flipperzero-slots#1]
The game is unbalanced,

It favors the house too much, maybe if you win you dont lose the money you bet? So now it becomes more fair... as most bets even when won give 2/3 of what you betted on...

**Comment by Daniel-dev-s** [comment]
feel free to open PR, i dont have much experience in balancing games)

**Comment by DefinetlyNotAI** [comment]
I am not that good at coding besides python and batch and powershell, but ill try my best :)
